### ISSUE TITLE
Links for Sidebar

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/r-i2p#7]
We cannot make guarantees about the continuing quality of any of the links provided. They will be removed if they become unavailable or if they are shown to be abusive in some way. Downtime and/or abuse reports for sites in the Reddit sidebar should be submitted to the moderation team for review.

**Browsing Resources**

**Proxy Configuration**
[I2P in Private Browsing Mode](https://addons.mozilla.org/en-US/firefox/addon/i2p-in-private-browsing/)
This extension is included in the I2P core Windows software. If you are not a Windows user, it can be added from Firefox Browser Add-ons.
[Configuring Privacy Browser for I2P on Android](https://eyedeekay.github.io/)
[Browser Configuration Guide](https://geti2p.net/en/about/browser-config)

**Outproxy**
[StormyCloud](https://stormycloud.org/)
[Purokishi](http://outproxy.purokishi.i2p/)

**Service Directories**
http://notbob.i2p/
http://identiguy.i2p/

**Search Engines**
[Legwork search engine](http://legwork.i2p/)
[Another i2p search engine by OnionLand](http://i2psearch.i2p/)
[Another i2p search engine provided by idk](http://yacy.idk.i2p/)

**Inproxies**
You can use inproxies to surf the I2P network without having to have an I2P router.
https://i2phides.me/
https://onion.ly/
https://www.darknetproxy.com/

**I2P Name Registries/ Directories**
[reg.i2p](http://reg.i2p/) operated by PurpleI2P Team
[dns.chudo.i2p](http://dns.chudo.i2p/)
[isitup.i2p](http://isitup.i2p/) Another I2P Name Registry and checking tools to see if a eepsite is offline.
http://notbob.i2p/
http://scanner.linuxfarm.i2p/
http://stats.i2p/

**File Sharing**
[PrivateBin](http://paste.r4sas.i2p/) Encrypted pastebin
http://sharefile.i2p/
http://fileshare.linuxfarm.i2p/
http://cake.i2p/
http://tmpsend.i2p/

**Pastebins**
http://privatebin.i2p/
http://paste.idk.i2p/

**Torrents**
[PaTracker](http://tracker2.postman.i2p/) Main torrent tracker
[DifTracker](http://diftracker.i2p/) (French) torrent tracker

**YouTube Proxy**
http://tube.i2p/
http://invidious.qwik.i2p/

**Twitter Proxy**
http://natter.i2p/
http://nitter.skank.i2p/

**Wikipedia Proxy**
http://wikiless.i2p/

**News**
http://planet.i2p/

**I2P Related**
http://i2p-projekt.i2p/
http://wiki.i2p-projekt.i2p/
http://i2pmetrics.i2p/

**Tutorials**
http://privacy-handbuch.i2p/
[Setting Up A Gopher Service on I2P](http://digitalsr.i2p/computing/gopher.html)
A gopher service is somewhere in between a website and an ftp server, allowing the user to download files and also access links.
[Generating an eepsite vanity address](https://www.bentasker.co.uk/posts/documentation/general/generating-an-i2p-eepsite-vanity-address.html#) (i2pd)
[Multi-homing a site between the WWW and an I2P Eepsite](https://www.bentasker.co.uk/posts/blog/privacy/multi-homing-a-site-between-www-and-i2p-eepsite.html#) (i2pd)
[How to set up untraceable websites (eepsites) on I2P](https://mhatta.medium.com/how-to-set-up-untraceable-websites-eepsites-on-i2p-1fe26069271d)
[Easy censorship-resistant communication with Syndie](https://mhatta.medium.com/easy-censorship-resistant-communication-with-syndie-e063a6c9cf35)
[The Hitchhiker’s Guide to the I2P eepsites](https://mhatta.medium.com/the-hitchhikers-guide-to-the-i2p-eepsites-e4dfe6bb7a45)

**I2P Core Development Forums and Gitlab**
[Core project site](http://i2p-projekt.i2p/) ([clearnet](https://geti2p.net/en/))
[I2P Forum](http://i2pforum.i2p/) ([clearnet](https://i2pforum.net/)) Official I2P community and development forum
[zzz](http://zzz.i2p/) zzz's personal website, developers forum

[Inside I2P - (http://git.idk.i2p)](http://git.idk.i2p/)
[Outside I2P - (https://i2pgit.org)](https://i2pgit.org/)
git clone https://i2pgit.org/i2p-hackers/i2p.i2p.git
The read-only mirror is also still available at github.

[GitHub mirror](https://github.com/i2p/i2p.i2p)
git clone https://github.com/i2p/i2p.i2p.git

**The Tor Project is not I2P's competition, surveillance and creeping authoritarianism is.**
Support Tor users
[Blizzard: The I2P Snowflake donor Plugin](https://eyedeekay.github.io/)

**I Found A Bug!**
[I2P Core Java Software, clearnet](https://i2pgit.org/i2p-hackers/i2p.i2p) 
[I2P Core Java Software, I2P Network](http://git.idk.i2p/i2p-hackers/i2p.i2p) 
[Android, clearnet](https://i2pgit.org/i2p-hackers/i2p.android.base)
[Android, I2P Network](http://git.idk.i2p/i2p-hackers/i2p.android.base) 
[I2P Firefox profile + Freestanding Jpackage(Easy-install), clearnet](https://i2pgit.org/i2p-hackers/i2p.firefox) 
[I2P Firefox profile + Freestanding Jpackage(Easy-install), I2P Network](http://git.idk.i2p/i2p-hackers/i2p.firefox) 
[Certified DMG + Freestanding Jpackage(Easy-install Mac), clearnet](https://i2pgit.org/i2p-hackers/i2p-jpackage-mac) 
[Certified DMG + Freestanding Jpackage(Easy-install Mac), I2P Network](http://git.idk.i2p/i2p-hackers/i2p-jpackage-mac) 

[There is also a .onion endpoint](http://47ggr2fa3vnwfyhvgskzdmr3i32eijwymxohtxsls45dulmriwxszjad.onion/)

**Comment by marek22k** [comment]
New links: https://github.com/Shoalsteed/r-i2p/issues/1#issuecomment-1323221013

**Comment by Shoalsteed** [comment]
> New links: [#1 (comment)](https://github.com/Shoalsteed/r-i2p/issues/1#issuecomment-1323221013)

Added - I do not have the name of the services however only the links.

**Comment by Shoalsteed** [comment]
It might be a good idea to have a very brief description of each link for services.

**Comment by marek22k** [comment]
I think most things are self-explanatory. We also have headings like "Wikipedia Proxy", "Pastebin", ...
To the following links I would only add descriptions:

I2P Related
http://i2p-projekt.i2p/ - Official site of I2P
http://wiki.i2p-projekt.i2p/ - Internal I2P wiki maintained by the I2P team
http://i2pmetrics.i2p/ - Statistics about routers in I2P (countries, flags, ...)

Tutorials
http://w3schools.i2p/ - Online courses about web technologies like HTML, CSS or JavaScript
http://privacy-handbuch.i2p/ - Manual in German with tips on how to protect ones privacy

News
http://planet.i2p/ - RSS News Aggreator

I2P Name Registries/ Directories
[reg.i2p](http://reg.i2p/) operated by PurpleI2P Team - DNS service
[dns.chudo.i2p](http://dns.chudo.i2p/) - DNS service
[isitup.i2p](http://isitup.i2p/) Another I2P Name Registry and checking tools to see if a eepsite is offline.
http://notbob.i2p/ - Lists active eepsites and categorizes them.
http://scanner.linuxfarm.i2p/ - Copy from notbob.i2p
http://stats.i2p/ - DNS service and router statistics

I am unsure about the description of http://scanner.linuxfarm.i2p/. However, it looks like a copy of nobbob.i2p.

**Comment by Shoalsteed** [comment]
I strongly suggest a disclaimer .

**Comment by eyedeekay** [comment]
ACK on all the links. I would suggest that the disclaimer read to the effect:

```md
These links are curated by the moderation team and periodically visited by them. However, they are not operated by the I2P Project, nor my members of the r/i2p moderation team, and cannot be guaranteed to be available at any given time. We cannot make guarantees about the continuing quality of any of their content. They will be removed if they become unavailable or if they are shown to be abusive in some way. Downtime and/or abuse reports for sites in the Reddit sidebar should be submitted to the moderation team for review.
```

**Comment by Shoalsteed** [comment]
I think that this is ready for implementation.

@marek22k - did you begin a draft for sidebar updates?

**Comment by marek22k** [comment]
We can remove dns.chudo.i2p (see https://github.com/wipedlifepotato/dns.chudo.i2p/issues/2).

**Comment by marek22k** [comment]
> @marek22k - did you begin a draft for sidebar updates?

In what way do you mean with draft? I could take the changes to Reddit. For that I only need the markdown for the links.

Something like https://github.com/Shoalsteed/r-i2p/blob/main/sidebar.md?

Do you have an idea for a better description of http://scanner.linuxfarm.i2p/ ?

**Comment by marek22k** [comment]
>  http://identiguy.i2p/

I think we should remove this link.

**Comment by Shoalsteed** [comment]
@marek22k ACK- I looked at the file and I think we are all set!
