### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/r-i2p#9]
I suggest that we bump the DNM Rule up to number 3 and change the copy to be more direct:

Questions about specific services will result in your post being removed and being banned due to recent spam and abuse.
We can't and won't help you troubleshoot finding or connecting to Darknet Markets and related services. We cannot help you, we won't help you, don't ask.
We cannot help you with accounts on individual I2P services of any kind. To troubleshoot those accounts, you should contact the admin of the service.

**Comment by Shoalsteed** [comment]
@marek22k what do you think about changing this?

**Comment by marek22k** [comment]
I think that's a good idea. However, I have the feeling that no one reads through the rules. Should I change that now?

**Comment by Shoalsteed** [comment]
> I think that's a good idea. However, I have the feeling that no one reads through the rules. Should I change that now?

Yes please - I agree that people may not read the rules, but it is worth a try.

**Comment by marek22k** [comment]
Should the title stay like this or do we change it too? Currently the title is "We can't and won't help you troubleshoot accounts on Darknet Markets and related services".

**Comment by Shoalsteed** [comment]
> Should the title stay like this or do we change it too? Currently the title is "We can't and won't help you troubleshoot accounts on Darknet Markets and related services".

I would leave the title

**Comment by Shoalsteed** [comment]
I see the update - closing the issue
